name: Test suite
on:
  push:
    branches: [main]
  pull_request:
    branches: [main, develop, dependabot]
  workflow_dispatch:

env:
  TESTS_DATABASE_USERNAME: "root"
  TESTS_DATABASE_PASSWORD: "root"

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.11"]
        poetry-version: ["1.5"]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - uses: abatilo/actions-poetry@v2
        with:
          poetry-version: ${{ matrix.poetry-version }}

      - uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Set up MySQL
        run: |
          sudo /etc/init.d/mysql start

      - name: Install Python dependencies
        run: poetry install

      - name: Install JS dependencies
        run: npm install

      - name: Create config file
        run: cp ./scoop_witness_api/config.example.py ./scoop_witness_api/config.py

      - name: Run tests
        run: xvfb-run --auto-servernum -- poetry run pytest -v
